" Name:         spacvim
" Description:  Template for a colorscheme with dark and light variants
" Author:       Klaus-Peter Schreiner <kpschreiner13@gmail.com>
" Maintainer:   Myself <myself@somewhere.org>
" Website:      https://me.org
" License:      Public domain
" Last Updated: 23.10.2019 07:37:02

" Generated by Colortemplate v2.0.0

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'spacvim'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Keyword
hi! link Exception Statement
hi! link Float Constant
hi! link Include PreProc
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link Statement Special
hi! link StorageClass Type
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#292b2e', '#d26487', '#288668', '#b89f33',
          \ '#6981c5', '#a15ea7', '#35a8a5', '#999999', '#34323e', '#f2241f',
          \ '#67b11d', '#b1951d', '#4f97d7', '#bc6ec5', '#2d9574', '#b2b2b2']
    if get(g:, 'spacvim_transp_bg', 0) && !has('gui_running')
      hi Normal guifg=#999999 guibg=NONE guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#999999 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    else
      hi Normal guifg=#b2b2b2 guibg=#292b2e guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#999999 guibg=#292b2e guisp=NONE gui=NONE cterm=NONE
    endif
    hi ColorColumn guifg=NONE guibg=#212026 guisp=NONE gui=NONE cterm=NONE
    hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor guifg=#eead0e guibg=#292b2e guisp=NONE gui=reverse cterm=reverse
    hi CursorColumn guifg=fg guibg=#212026 guisp=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=#212026 guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#a15ea7 guibg=#292b2e guisp=NONE gui=NONE cterm=NONE
    hi DiffAdd guifg=#288668 guibg=NONE guisp=NONE gui=reverse cterm=reverse
    hi DiffChange guifg=#b89f33 guibg=NONE guisp=NONE gui=reverse cterm=reverse
    hi DiffDelete guifg=#d26487 guibg=NONE guisp=NONE gui=reverse cterm=reverse
    hi DiffText guifg=#6981c5 guibg=NONE guisp=NONE gui=reverse cterm=reverse
    hi Directory guifg=#6981c5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi EndOfBuffer guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ErrorMsg guifg=#e0211d guibg=#b2b2b2 guisp=NONE gui=reverse cterm=reverse
    hi FoldColumn guifg=#a15ea7 guibg=#100a14 guisp=NONE gui=NONE cterm=NONE
    hi Folded guifg=#4f97d7 guibg=#293239 guisp=NONE gui=bold,italic cterm=bold,italic
    hi IncSearch guifg=#35a8a5 guibg=NONE guisp=NONE gui=standout cterm=standout
    hi LineNr guifg=#44505c guibg=#212026 guisp=NONE gui=NONE cterm=NONE
    hi MatchParen guifg=#86dc2f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi ModeMsg guifg=#6981c5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi MoreMsg guifg=#6981c5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi NonText guifg=#d26487 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Pmenu guifg=#9a9aba guibg=#34323e guisp=NONE gui=NONE cterm=NONE
    hi PmenuSbar guifg=NONE guibg=#34323e guisp=NONE gui=NONE cterm=NONE
    hi PmenuSel guifg=#b2b2b2 guibg=#5e5079 guisp=NONE gui=NONE cterm=NONE
    hi PmenuThumb guifg=NONE guibg=#5e5079 guisp=NONE gui=NONE cterm=NONE
    hi Question guifg=#35a8a5 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Search guifg=#67b11d guibg=NONE guisp=NONE gui=reverse cterm=reverse
    hi SignColumn guifg=#b2b2b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi SpecialKey guifg=#686868 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi SpellBad guifg=NONE guibg=NONE guisp=#d26487 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap guifg=NONE guibg=NONE guisp=#6981c5 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal guifg=NONE guibg=NONE guisp=#a15ea7 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare guifg=NONE guibg=NONE guisp=#35a8a5 gui=reverse,undercurl ctermfg=NONE ctermbg=NONE cterm=reverse,undercurl
    hi StatusLine guifg=#b2b2b2 guibg=#222226 guisp=NONE gui=NONE cterm=NONE
    hi StatusLineNC guifg=#686868 guibg=#222226 guisp=NONE gui=NONE cterm=NONE
    hi TabLine guifg=#b2b2b2 guibg=#222226 guisp=NONE gui=NONE cterm=NONE
    hi TabLineFill guifg=NONE guibg=#0a0814 guisp=NONE gui=NONE cterm=NONE
    hi TabLineSel guifg=#b2b2b2 guibg=#5d4d7a guisp=NONE gui=NONE cterm=NONE
    hi Title guifg=#b89f33 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi VertSplit guifg=#5d4d7a guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Visual guifg=NONE guibg=#444155 guisp=NONE gui=NONE cterm=NONE
    hi VisualNOS guifg=NONE guibg=#444155 guisp=NONE gui=NONE cterm=NONE
    hi WarningMsg guifg=#dc752f guibg=#b2b2b2 guisp=NONE gui=reverse cterm=reverse
    hi WildMenu guifg=#bc6ec5 guibg=#3b314d guisp=NONE gui=NONE cterm=NONE
    hi Comment guifg=#2aa1ae guibg=#292e34 guisp=NONE gui=italic cterm=italic
    hi Constant guifg=#a45bad guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi String guifg=#2d9574 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Error guifg=#e0211d guibg=#292b2e guisp=NONE gui=reverse cterm=reverse
    hi Function guifg=#bc6ec5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Identifier guifg=#7590db guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Ignore guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Keyword guifg=#4f97d7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi PreProc guifg=#9f8766 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Special guifg=#4f97d7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Todo guifg=#2aa1ae guibg=#292e34 guisp=NONE gui=bold cterm=bold
    hi Type guifg=#ce537a guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorIM guifg=#eead0e guibg=#292b2e guisp=NONE gui=reverse cterm=reverse
    hi ToolbarLine guifg=NONE guibg=#212026 guisp=NONE gui=NONE cterm=NONE
    hi ToolbarButton guifg=#b2b2b2 guibg=#212026 guisp=NONE gui=bold cterm=bold
    if !s:italics
      hi Folded gui=bold cterm=bold
      hi Comment gui=NONE cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#292b2e', '#d26487', '#288668', '#b89f33',
        \ '#6981c5', '#a15ea7', '#35a8a5', '#999999', '#34323e', '#f2241f',
        \ '#67b11d', '#b1951d', '#4f97d7', '#bc6ec5', '#2d9574', '#b2b2b2']
  if get(g:, 'spacvim_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#999999 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#999999 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#655370 guibg=#fbf8ef guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#999999 guibg=#292b2e guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#efeae9 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#eead0e guibg=#fbf8ef guisp=NONE gui=reverse cterm=reverse
  hi CursorColumn guifg=fg guibg=#efeae9 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#efeae9 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#a15ea7 guibg=#fbf8ef guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#288668 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#b89f33 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#d26487 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#6981c5 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi Directory guifg=#6981c5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg guifg=#e0211d guibg=#e7e5eb guisp=NONE gui=reverse cterm=reverse
  hi FoldColumn guifg=#a15ea7 guibg=#e3dedd guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#3a81c3 guibg=#edf1ed guisp=NONE gui=bold,italic cterm=bold,italic
  hi IncSearch guifg=#35a8a5 guibg=NONE guisp=NONE gui=standout cterm=standout
  hi LineNr guifg=#a8a8bf guibg=#efeae9 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#ba2f59 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#6981c5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#6981c5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#d26487 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Pmenu guifg=#8c799f guibg=#e2e0ea guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#e2e0ea guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#655370 guibg=#c8c6dd guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#c8c6dd guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#35a8a5 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Search guifg=#67b11d guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi SignColumn guifg=#655370 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#a094a2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#d26487 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#6981c5 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#a15ea7 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#35a8a5 gui=reverse,undercurl ctermfg=NONE ctermbg=NONE cterm=reverse,undercurl
  hi StatusLine guifg=#655370 guibg=#e7e5eb guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#a094a2 guibg=#e7e5eb guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#655370 guibg=#e7e5eb guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#d2ceda guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#655370 guibg=#d3d3e7 guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#b89f33 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi VertSplit guifg=#b3b9be guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#d3d3e7 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#d3d3e7 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#dc752f guibg=#e7e5eb guisp=NONE gui=reverse cterm=reverse
  hi WildMenu guifg=#bc6ec5 guibg=#e7e7fc guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#2aa1ae guibg=#ecf3ec guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#4e3163 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#2d9574 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#e0211d guibg=#292b2e guisp=NONE gui=reverse cterm=reverse
  hi Function guifg=#6c3163 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#715ab1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Keyword guifg=#3a81c3 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi PreProc guifg=#da8b55 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#3a81c3 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Todo guifg=#2aa1ae guibg=#ecf3ec guisp=NONE gui=bold cterm=bold
  hi Type guifg=#ba2f59 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=#eead0e guibg=#fbf8ef guisp=NONE gui=reverse cterm=reverse
  hi ToolbarLine guifg=NONE guibg=#efeae9 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#655370 guibg=#efeae9 guisp=NONE gui=bold cterm=bold
  if !s:italics
    hi Folded gui=bold cterm=bold
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    if get(g:, 'spacvim_transp_bg', 0)
      hi Normal ctermfg=247 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=247 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=249 ctermbg=235 cterm=NONE
      if !has('patch-8.0.0616') " Fix for Vim bug
        set background=dark
      endif
      hi Terminal ctermfg=247 ctermbg=235 cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=234 cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=214 ctermbg=235 cterm=reverse
    hi CursorColumn ctermfg=fg ctermbg=234 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=234 cterm=NONE
    hi CursorLineNr ctermfg=133 ctermbg=235 cterm=NONE
    hi DiffAdd ctermfg=29 ctermbg=NONE cterm=reverse
    hi DiffChange ctermfg=178 ctermbg=NONE cterm=reverse
    hi DiffDelete ctermfg=168 ctermbg=NONE cterm=reverse
    hi DiffText ctermfg=68 ctermbg=NONE cterm=reverse
    hi Directory ctermfg=68 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ErrorMsg ctermfg=160 ctermbg=249 cterm=reverse
    hi FoldColumn ctermfg=133 ctermbg=232 cterm=NONE
    hi Folded ctermfg=32 ctermbg=236 cterm=bold,italic
    hi IncSearch ctermfg=37 ctermbg=NONE cterm=standout
    hi LineNr ctermfg=239 ctermbg=234 cterm=NONE
    hi MatchParen ctermfg=112 ctermbg=NONE cterm=NONE
    hi ModeMsg ctermfg=68 ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=68 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=168 ctermbg=NONE cterm=bold
    hi Pmenu ctermfg=103 ctermbg=236 cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=236 cterm=NONE
    hi PmenuSel ctermfg=249 ctermbg=60 cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=60 cterm=NONE
    hi Question ctermfg=37 ctermbg=NONE cterm=bold
    hi Search ctermfg=70 ctermbg=NONE cterm=reverse
    hi SignColumn ctermfg=249 ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=242 ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=reverse
    hi StatusLine ctermfg=249 ctermbg=235 cterm=NONE
    hi StatusLineNC ctermfg=242 ctermbg=235 cterm=NONE
    hi TabLine ctermfg=249 ctermbg=235 cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=232 cterm=NONE
    hi TabLineSel ctermfg=249 ctermbg=60 cterm=NONE
    hi Title ctermfg=178 ctermbg=NONE cterm=bold
    hi VertSplit ctermfg=60 ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=238 cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=238 cterm=NONE
    hi WarningMsg ctermfg=166 ctermbg=249 cterm=reverse
    hi WildMenu ctermfg=170 ctermbg=237 cterm=NONE
    hi Comment ctermfg=37 ctermbg=236 cterm=italic
    hi Constant ctermfg=133 ctermbg=NONE cterm=NONE
    hi String ctermfg=29 ctermbg=NONE cterm=NONE
    hi Error ctermfg=160 ctermbg=235 cterm=reverse
    hi Function ctermfg=170 ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=68 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=32 ctermbg=NONE cterm=bold
    hi PreProc ctermfg=137 ctermbg=NONE cterm=NONE
    hi Special ctermfg=32 ctermbg=NONE cterm=bold
    hi Todo ctermfg=37 ctermbg=236 cterm=bold
    hi Type ctermfg=168 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=214 ctermbg=235 cterm=reverse
    hi ToolbarLine ctermfg=NONE ctermbg=234 cterm=NONE
    hi ToolbarButton ctermfg=249 ctermbg=234 cterm=bold
    if !s:italics
      hi Folded cterm=bold
      hi Comment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'spacvim_transp_bg', 0)
    hi Normal ctermfg=247 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=247 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=60 ctermbg=231 cterm=NONE
    hi Terminal ctermfg=247 ctermbg=235 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=214 ctermbg=231 cterm=reverse
  hi CursorColumn ctermfg=fg ctermbg=255 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLineNr ctermfg=133 ctermbg=231 cterm=NONE
  hi DiffAdd ctermfg=29 ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=178 ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=168 ctermbg=NONE cterm=reverse
  hi DiffText ctermfg=68 ctermbg=NONE cterm=reverse
  hi Directory ctermfg=68 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=160 ctermbg=254 cterm=reverse
  hi FoldColumn ctermfg=133 ctermbg=254 cterm=NONE
  hi Folded ctermfg=32 ctermbg=255 cterm=bold,italic
  hi IncSearch ctermfg=37 ctermbg=NONE cterm=standout
  hi LineNr ctermfg=146 ctermbg=255 cterm=NONE
  hi MatchParen ctermfg=161 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=68 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=68 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=168 ctermbg=NONE cterm=bold
  hi Pmenu ctermfg=103 ctermbg=254 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=254 cterm=NONE
  hi PmenuSel ctermfg=60 ctermbg=189 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=189 cterm=NONE
  hi Question ctermfg=37 ctermbg=NONE cterm=bold
  hi Search ctermfg=70 ctermbg=NONE cterm=reverse
  hi SignColumn ctermfg=60 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=reverse
  hi StatusLine ctermfg=60 ctermbg=254 cterm=NONE
  hi StatusLineNC ctermfg=246 ctermbg=254 cterm=NONE
  hi TabLine ctermfg=60 ctermbg=254 cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=252 cterm=NONE
  hi TabLineSel ctermfg=60 ctermbg=189 cterm=NONE
  hi Title ctermfg=178 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=250 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=189 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=189 cterm=NONE
  hi WarningMsg ctermfg=166 ctermbg=254 cterm=reverse
  hi WildMenu ctermfg=170 ctermbg=189 cterm=NONE
  hi Comment ctermfg=37 ctermbg=255 cterm=italic
  hi Constant ctermfg=53 ctermbg=NONE cterm=NONE
  hi String ctermfg=29 ctermbg=NONE cterm=NONE
  hi Error ctermfg=160 ctermbg=235 cterm=reverse
  hi Function ctermfg=89 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=61 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=32 ctermbg=NONE cterm=bold
  hi PreProc ctermfg=173 ctermbg=NONE cterm=NONE
  hi Special ctermfg=32 ctermbg=NONE cterm=bold
  hi Todo ctermfg=37 ctermbg=255 cterm=bold
  hi Type ctermfg=161 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=214 ctermbg=231 cterm=reverse
  hi ToolbarLine ctermfg=NONE ctermbg=255 cterm=NONE
  hi ToolbarButton ctermfg=60 ctermbg=255 cterm=bold
  if !s:italics
    hi Folded cterm=bold
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    if get(g:, 'spacvim_transp_bg', 0)
      hi Normal ctermfg=white ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=white ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=white ctermbg=black cterm=NONE
      hi Terminal ctermfg=white ctermbg=black cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=black cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=yellow ctermbg=black cterm=reverse
    hi CursorColumn ctermfg=fg ctermbg=black cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=black cterm=NONE
    hi CursorLineNr ctermfg=magenta ctermbg=black cterm=NONE
    hi DiffAdd ctermfg=green ctermbg=NONE cterm=reverse
    hi DiffChange ctermfg=yellow ctermbg=NONE cterm=reverse
    hi DiffDelete ctermfg=red ctermbg=NONE cterm=reverse
    hi DiffText ctermfg=blue ctermbg=NONE cterm=reverse
    hi Directory ctermfg=blue ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ErrorMsg ctermfg=red ctermbg=white cterm=reverse
    hi FoldColumn ctermfg=magenta ctermbg=black cterm=NONE
    hi Folded ctermfg=blue ctermbg=black cterm=bold,italic
    hi IncSearch ctermfg=cyan ctermbg=NONE cterm=standout
    hi LineNr ctermfg=gray ctermbg=black cterm=NONE
    hi MatchParen ctermfg=green ctermbg=NONE cterm=NONE
    hi ModeMsg ctermfg=blue ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=blue ctermbg=NONE cterm=NONE
    hi NonText ctermfg=red ctermbg=NONE cterm=bold
    hi Pmenu ctermfg=magenta ctermbg=magenta cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=magenta cterm=NONE
    hi PmenuSel ctermfg=white ctermbg=black cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=black cterm=NONE
    hi Question ctermfg=cyan ctermbg=NONE cterm=bold
    hi Search ctermfg=green ctermbg=NONE cterm=reverse
    hi SignColumn ctermfg=white ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=gray ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=reverse
    hi StatusLine ctermfg=white ctermbg=black cterm=NONE
    hi StatusLineNC ctermfg=gray ctermbg=black cterm=NONE
    hi TabLine ctermfg=white ctermbg=black cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=black cterm=NONE
    hi TabLineSel ctermfg=white ctermbg=gray cterm=NONE
    hi Title ctermfg=yellow ctermbg=NONE cterm=bold
    hi VertSplit ctermfg=magenta ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=gray cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=gray cterm=NONE
    hi WarningMsg ctermfg=yellow ctermbg=white cterm=reverse
    hi WildMenu ctermfg=magenta ctermbg=gray cterm=NONE
    hi Comment ctermfg=cyan ctermbg=black cterm=italic
    hi Constant ctermfg=magenta ctermbg=NONE cterm=NONE
    hi String ctermfg=green ctermbg=NONE cterm=NONE
    hi Error ctermfg=red ctermbg=black cterm=reverse
    hi Function ctermfg=magenta ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=blue ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=blue ctermbg=NONE cterm=bold
    hi PreProc ctermfg=yellow ctermbg=NONE cterm=NONE
    hi Special ctermfg=blue ctermbg=NONE cterm=bold
    hi Todo ctermfg=cyan ctermbg=black cterm=bold
    hi Type ctermfg=magenta ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=yellow ctermbg=black cterm=reverse
    hi ToolbarLine ctermfg=NONE ctermbg=black cterm=NONE
    hi ToolbarButton ctermfg=white ctermbg=black cterm=bold
    if !s:italics
      hi Folded cterm=bold
      hi Comment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'spacvim_transp_bg', 0)
    hi Normal ctermfg=white ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=white ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=white ctermbg=black cterm=NONE
    hi Terminal ctermfg=white ctermbg=black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=black cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=yellow ctermbg=black cterm=reverse
  hi CursorColumn ctermfg=fg ctermbg=black cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=black cterm=NONE
  hi CursorLineNr ctermfg=magenta ctermbg=black cterm=NONE
  hi DiffAdd ctermfg=green ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=yellow ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=red ctermbg=NONE cterm=reverse
  hi DiffText ctermfg=blue ctermbg=NONE cterm=reverse
  hi Directory ctermfg=blue ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=red ctermbg=black cterm=reverse
  hi FoldColumn ctermfg=magenta ctermbg=black cterm=NONE
  hi Folded ctermfg=blue ctermbg=black cterm=bold,italic
  hi IncSearch ctermfg=cyan ctermbg=NONE cterm=standout
  hi LineNr ctermfg=gray ctermbg=black cterm=NONE
  hi MatchParen ctermfg=green ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=blue ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=blue ctermbg=NONE cterm=NONE
  hi NonText ctermfg=red ctermbg=NONE cterm=bold
  hi Pmenu ctermfg=magenta ctermbg=magenta cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=magenta cterm=NONE
  hi PmenuSel ctermfg=white ctermbg=black cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=black cterm=NONE
  hi Question ctermfg=cyan ctermbg=NONE cterm=bold
  hi Search ctermfg=green ctermbg=NONE cterm=reverse
  hi SignColumn ctermfg=white ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=gray ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=reverse
  hi StatusLine ctermfg=white ctermbg=black cterm=NONE
  hi StatusLineNC ctermfg=gray ctermbg=black cterm=NONE
  hi TabLine ctermfg=white ctermbg=black cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=black cterm=NONE
  hi TabLineSel ctermfg=white ctermbg=gray cterm=NONE
  hi Title ctermfg=yellow ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=magenta ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=gray cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=gray cterm=NONE
  hi WarningMsg ctermfg=yellow ctermbg=black cterm=reverse
  hi WildMenu ctermfg=magenta ctermbg=gray cterm=NONE
  hi Comment ctermfg=cyan ctermbg=black cterm=italic
  hi Constant ctermfg=magenta ctermbg=NONE cterm=NONE
  hi String ctermfg=green ctermbg=NONE cterm=NONE
  hi Error ctermfg=red ctermbg=black cterm=reverse
  hi Function ctermfg=magenta ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=blue ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=blue ctermbg=NONE cterm=bold
  hi PreProc ctermfg=yellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=blue ctermbg=NONE cterm=bold
  hi Todo ctermfg=cyan ctermbg=black cterm=bold
  hi Type ctermfg=magenta ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=yellow ctermbg=black cterm=reverse
  hi ToolbarLine ctermfg=NONE ctermbg=black cterm=NONE
  hi ToolbarButton ctermfg=white ctermbg=black cterm=bold
  if !s:italics
    hi Folded cterm=bold
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: act1                 #222226                  ~        black
" Color: act2                 #5d4d7a                  ~        gray
" Color: base                 #b2b2b2                  ~        white
" Color: base_dim             #686868                  ~        gray
" Color: bg1                  #292b2e                  ~        black
" Color: bg2                  #212026                  ~        black
" Color: bg3                  #100a14                  ~        black
" Color: bg4                  #0a0814                  ~        black
" Color: border               #5d4d7a                  ~        magenta
" Color: cblk                 #cbc1d5                  ~
" Color: cblk_bg              #2f2b33                  ~
" Color: cblk_ln              #827591                  ~
" Color: cblk_ln_bg           #373040                  ~
" Color: cursor               #eead0e                  ~        yellow
" Color: const                #a45bad                  ~        magenta
" Color: comment              #2aa1ae                  ~        cyan
" Color: comment_light        #2aa1ae                  ~        cyan
" Color: comment_bg           #292e34                  ~        black
" Color: comp                 #c56ec3                  ~
" Color: err                  #e0211d                  ~        red
" Color: func                 #bc6ec5                  ~        magenta
" Color: head1                #4f97d7                  ~        blue
" Color: head1_bg             #293239                  ~        black
" Color: head2                #2d9574                  ~
" Color: head2_bg             #293235                  ~
" Color: head3                #67b11d                  ~
" Color: head3_bg             #293235                  ~
" Color: head4                #b1951d                  ~
" Color: head4_bg             #32322c                  ~
" Color: highlight            #444155                  ~         gray
" Color: highlight_dim        #3b314d                  ~         gray
" Color: keyword              #4f97d7                  ~         blue
" Color: lnum                 #44505c                  ~         gray
" Color: mat                  #86dc2f                  ~         green
" Color: meta                 #9f8766                  ~         yellow
" Color: str                  #2d9574                  ~         green
" Color: suc                  #86dc2f                  ~
" Color: ttip                 #9a9aba                  ~         magenta
" Color: ttip_sl              #5e5079                  ~         black
" Color: ttip_bg              #34323e                  ~         magenta
" Color: type                 #ce537a                  ~         magenta
" Color: var                  #7590db                  ~         blue
" Color: war                  #dc752f                  ~         yellow
" Color: black                #292b2e                  ~         black
" Color: red                  #d26487                  ~         red
" Color: green                #288668                  ~         green
" Color: yellow               #b89f33                  ~         yellow
" Color: blue                 #6981c5                  ~         blue
" Color: magenta              #a15ea7                  ~         magenta
" Color: cyan                 #35a8a5                  ~         cyan
" Color: white                #999999                  ~         white
" Color: brightblack          #34323e                  ~        
" Color: brightred            #f2241f                  ~         
" Color: brightgreen          #67b11d                  ~         green
" Color: brightyellow         #b1951d                  ~
" Color: brightblue           #4f97d7                  ~
" Color: brightmagenta        #bc6ec5                  ~         magenta
" Color: brightcyan           #2d9574                  ~
" Color: brightwhite          #b2b2b2                  ~
" Color: pink                 #ff82b1                  ~         magenta
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" Background: light
" Color: act1                 #e7e5eb                  ~        black
" Color: act2                 #d3d3e7                  ~        gray
" Color: base                 #655370                  ~        white
" Color: base_dim             #a094a2                  ~        gray
" Color: bg1                  #fbf8ef                  ~        black
" Color: bg2                  #efeae9                  ~        black
" Color: bg3                  #e3dedd                  ~        black
" Color: bg4                  #d2ceda                  ~        black
" Color: border               #b3b9be                  ~        magenta
" Color: cblk                 #655370                  ~
" Color: cblk_bg              #e8e3f0                  ~
" Color: cblk_ln              #9380b2                  ~
" Color: cblk_ln_bg           #ddd8eb                  ~
" Color: cursor               #eead0e                  ~        yellow
" Color: const                #4e3163                  ~        magenta
" Color: comment              #2aa1ae                  ~        cyan
" Color: comment_light        #a49da5                  ~        cyan
" Color: comment_bg           #ecf3ec                  ~        black
" Color: comp                 #6c4173                  ~
" Color: err                  #e0211d                  ~        red
" Color: func                 #6c3163                  ~        magenta
" Color: head1                #3a81c3                  ~        blue
" Color: head1_bg             #edf1ed                  ~        black
" Color: head2                #2d9574                  ~
" Color: head2_bg             #edf2e9                  ~
" Color: head3                #67b11d                  ~
" Color: head3_bg             #edf2e9                  ~
" Color: head4                #b1951d                  ~
" Color: head4_bg             #f6f1e1                  ~
" Color: highlight            #d3d3e7                  ~         gray
" Color: highlight_dim        #e7e7fc                  ~         gray
" Color: keyword              #3a81c3                  ~         blue
" Color: lnum                 #a8a8bf                  ~         gray
" Color: mat                  #ba2f59                  ~         green
" Color: meta                 #da8b55                  ~         yellow
" Color: str                  #2d9574                  ~         green
" Color: suc                  #42ae2c                  ~
" Color: ttip                 #8c799f                  ~         magenta
" Color: ttip_sl              #c8c6dd                  ~         black
" Color: ttip_bg              #e2e0ea                  ~         magenta
" Color: type                 #ba2f59                  ~         magenta
" Color: var                  #715ab1                  ~         blue
" Color: war                  #dc752f                  ~         yellow
" Color: black                #292b2e                  ~         black
" Color: red                  #d26487                  ~         red
" Color: green                #288668                  ~         green
" Color: yellow               #b89f33                  ~         yellow
" Color: blue                 #6981c5                  ~         blue
" Color: magenta              #a15ea7                  ~         magenta
" Color: cyan                 #35a8a5                  ~         cyan
" Color: white                #999999                  ~         white
" Color: brightblack          #34323e                  ~        
" Color: brightred            #f2241f                  ~         
" Color: brightgreen          #67b11d                  ~         green
" Color: brightyellow         #b1951d                  ~
" Color: brightblue           #4f97d7                  ~
" Color: brightmagenta        #bc6ec5                  ~         magenta
" Color: brightcyan           #2d9574                  ~
" Color: brightwhite          #b2b2b2                  ~
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" Background: any
" vim: et ts=2 sw=2
